# Replicate https://github.com/gitpod-io/gitpod/issues/5862
tasks:   
  - command: |
      clear
      echo "Creating 3GB file"
      dd if=/dev/zero of=3gb-file bs=1024 count=3072000
      echo "Creating 1GB file"
      dd if=/dev/zero of=1gb-file--to-delete bs=1024 count=1024000
      echo "Displaying /workspace size"
      du -sh /workspace
      echo "1) /worksapce is larger than 3GB (4GB)"
      echo "2) Click on main menu and select 'Gitpod: Share Workspace Snapshot'"
      echo "3) Snapshot is expected to fail :("
      echo "3) Delete the file '1gb-file--to-delete'"
      echo "4) Run 'du -sh /workspace'"
      echo "5) /workspace is exactly 3GB"
      echo "6) Select again 'Gitpod: Share Workspace Snapshot'"
      echo "7) Snapshot is expected to run successfully"
